Flaque/quirk

- package.json
- src/CBTFormScreen.tsx
- src/CBTListScreen.tsx
Fixes #17, also standardizes labels.
> Fix headers, fix form screen behavior, add deploy script

- src/distortions.ts
- src/theme.ts
- src/ui.tsx
Better Distortion selecting, cleaned up redundant ones.
> Clean up Cognitive Distortions

- package.json
- src/CBTForm.tsx
- src/CBTFormScreen.tsx
- src/CBTListScreen.tsx
- yarn.lock
> Small UI Fixes

- src/CBTFormScreen.tsx
- src/distortions.ts
- src/store.ts
- src/ui.tsx
> Fixes a bunch of small bugs

- package.json
- src/CBTForm.tsx
- src/i18n.ts
- src/locals/en.json
- src/locals/fr.json
- src/typings.d.ts
- yarn.lock
This is a demo of localization. Let me know if you want me to continue out the English version! Currently it defaults to English if we don't have the language too. One thing you mentioned is you don't want to wait until all versions are translated until you release. I believe it would be best to either use google translate for smaller things or worst case leave the one feature in English but add it to the (in this example) `fr.json` file. Someone else might know a better way to do this too so you don't need to wait for all the translations.
Also this will default to English if the users language isn't supported.
Go to iphone settings ➡️ general ➡️ language and region ➡️ select french.
Once you get back to the app it will look like this
> Localization

- src/distortions.ts
Distortions strings weren't localized.
> Adds  missing strings localization

- src/i18n.ts
- src/locals/pl.json
> Add Polish language

- src/locals/fi.json
Hei maailma!
Initial translation to [Finnish](https://en.wikipedia.org/wiki/Finnish_language).
There's probably further improvements to be made, but I'm not letting perfect be the enemy of good.
Note: to avoid a merge conflict, this PR only adds the `fi.json` file and does not import it in `src/i18n.ts`
> Add initial Finnish translations

- app.json
- src/i18n.ts
- src/locals/de.json
- src/locals/es.json
- src/locals/fi.json
- src/locals/ko.json
- src/locals/nl_NL.json
- src/locals/pl.json
- src/ui.tsx
This PR combines #53, #58, #57 and fixes a camel case issue.
Absolutely AMAZING work! Thank you so much! @devinroche @devilcius @kwierbol @idnovic!!!!!
> Add Spanish + German + Polish + Korean + Dutch + Finnish

- README.md
I did not translate the polish version :)
#58
> fixed contributor

- package.json
- src/CBTForm.tsx
- src/CBTFormScreen.tsx
- src/CBTListScreen.tsx
- src/i18n.ts
- src/locals/en.json
- src/setting/index.tsx
- src/ui.tsx
- yarn.lock
Adds accessibility labels to a bunch of buttons
> Add accessibility labels to icon buttons

- src/i18n.ts
- src/locals/zh-CN.json
Translated (with love) by Siying Chen, Xiaomin Lu, Baoqi Chen
> Adds Simplified Chinese translation

- src/locals/es.json
Quirk es una herramienta para Terapia Cognitiva Conductual (TCC). La TCC es uno de los tratamientos más efectivos y recetados para la depresión, ansiedad, ataques de pánico recurrentes y muchos otros problemas de salud mental. Quirk te ayuda a llevar un registro de tus "pensamientos automáticos", a cuestionarlos, y a entrenar tu cerebro con un pensamiento alternativo. La aplicación se encuentra bajo la licencia de código abierto GPL. Puedes encontrar el código en Github en: https://github.com/Flaque/quirk
Keywords:
Ansiedad, Depresión, Terapia Cognitiva Conductual, TCC, Pánico
> Fix typos and add clearer wordings in Spanish translation

- src/ExplanationScreen.tsx
- src/distortions.ts
Hey, can you add this to the master branch?  This fixes issue #59
> changed emoji to vampire for android fix

- App.ts
- src/CBTForm.tsx
- src/CBTFormScreen.tsx
- src/CBTOnBoarding.tsx
- src/ExplanationScreen.tsx
- src/alerter/index.tsx
- src/setting/index.tsx
- src/ui.tsx
* Refactors Onboarding
* `RoundedButton` => `ActionButton` 
* Adds onboarding button in help screen
> WIP: Add the ability to go back to onboarding screen

- App.ts
- src/CBTListScreen.tsx
Adds new buttons that take you back to the list. This fixes #93 and sets us up to have safer delete buttons.
> Add new buttons

- src/i18n.ts
- src/locals/pt-pt.json
Added portuguese (from portugal, that is, european portuguese). Hopefully the translation is good enough, but I plan to improve it if I find it lacking in certain areas.
> Added portugese (pt-pt)

- src/i18n.ts
- src/locals/nb.json
<details>
<summary>Original text</summary>
Quirk is a tool for Cognitive Behavioral Therapy (CBT). CBT is one of the most effective and widely prescribed treatments for depression, anxiety, panic disorder, and multiple other mental health problems.
Quirk helps you record "automatic thoughts," challenge them, and then train your brain with an alternative thought. The app is open source under the GPL. You can find the code on Github at: https://github.com/Flaque/quirk</details>
```
Quirk er et verktøy for kognitiv adferdsterapi (CBT). CBT er en av de mest effektive
og oftest foreskrevne behandlingene for depresjon, angst, panikk, og flere andre
mentalhelseproblemer.
Quirk hjelper deg å registrere "automatiske tanger," utfordre dem, og så trene hjernen
din med en alternativ tanke. Programmet …
```
> Add Norwegian Bokmål

- src/i18n.ts
- src/locals/it.json
Hi!
Thanks for this awesome project, it's it's particularly important to me.
I've added the italian translation, hit me up if you need more italian translations in the future!
**App store translation:**
Quirk è uno strumento per la Terapia Cognitivo Comportamentale (TCC). La TCC è uno dei trattamenti più efficaci ed utilizzati per aiutare la cura di depressione, ansia, attacchi di panico e molti altri problemi mentali.
Quirk ti aiuta ad annotare i "pensieri automatici", sfidarli e allenando il cervello a trovare un pensiero alternativo. L'app è open source sotto la licenza GPL. Puoi trovare il codice sorgente su GitHub Flaque/quirk
**Keywords:**
Ansia, Depressione, Terapia Cognitivo Comportamentale, TCC, Panico
I really hope it helps!
> Add Italian

- src/i18n.ts
- src/locals/sv.json
Hi! 
Thanks for creating this app!
Here's a translation of Quirk into swedish. 
Translation of the additional texts can be found below:
--- Appstore Description
Quirk är ett verktyg för Kognitiv Beteende Terapi (KBT). KBT är en av de mest effektiva och mest använda behandlingarna för depression, ångest, paniksyndrom och flera andra mentala hälsoproblem.   
Quirk hjälper dig att skriva ner "automatiska tankar", ifrågasätta dem och träna din hjärna med en alternativ tanke.
Appen är open source under GPL. Du hittar källkoden på Github här: 
https://github.com/Flaque/quirk
---
--- Keywords
Ångest, Depression, Kognitiv Beteende Terapi, KBT, Panik
---
> Add swedish

- src/locals/fr.json
-Quite a lot of changes to have a better match with the French language (mispells, coherence between unformal "you" and polite "you", typos)
-I also noticed some layout issues on smaller android screens, see screenshots below =)
-A few strings were hardcoded so they appear in English only (e.g. "no thoughts yet?"), please tell  me I you want me to go ahead with it !
> Updates for french translation

- src/i18n.ts
- src/locals/ro.json
Hello!
Here is the Romanian translation.
**App description:**
Quirk este o aplicație pentru Terapia Cognitiv-Comportamentală (TCC). TCC este unul dintre cele mai eficiente și recomandate tratamente pentru depresie, anxietate, tulburare de panică și multe alte probleme psihice.
Quirk te ajută să înregistrezi "gânduri automate", să le combați și să îți antrenezi mintea cu un gând alternativ. Aplicația este liberă și open-source sub licența GPL. Poți găsi codul pe Github aici: https://github.com/Flaque/quirk
**Keywords:**
Anxietate, Depresie, Terapie Cognitiv-Comportamentală, TCC, Panică
> Add Romanian

- src/locals/fr.json
The goal is to fix three minor typos I saw in the French translation. A secondary goal is to learn the contribution process. At first, I thought I should use the "translations" branch, but other contributors do not seem to have followed that pattern, hence the commit to master.
> Removed three spurious periods in French translations.

- src/locals/de.json
Improved German translation. Rebased on master.
> Update de.json - Rebase
